spring:
  cloud:
    gateway:
      routes:
        - id: catalog
          uri: ${rewrite.backend.uri:lb://catalog-service/}
          predicates:
            - Path=/catalog/**
          filters:
            - RewritePath=/pepeenmoto/(?<segment>.*),/catalog/$\{segment}
        - id: movies
          uri: ${rewrite.backend.uri:lb://movie-service/}
          predicates:
            - Path=/movies/**
          filters:
            - RewritePath=/movies/(?<segment>.*),/catalog/$\{segment}
debug: true
server:
  port: 8080
eureka:
  client:
    serviceURL:
      defaultZone: http://localhost:8761/eureka

management:
  endpoint:
    gateway:
      enabled: true

  endpoints:
    web:
      exposure:
        include: [health,gateway]
